### ISSUE TITLE
Cannot npm start in client

### ISSUE THREAD

**Issue by nguyen-tuan-hiep** [Shreehar01/Expert-AI#1]
This is the error when I npm start the client:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in ....

**Comment by Shreehar01** [comment]
Did you try `npm install` before `npm start`?

**Comment by nguyen-tuan-hiep** [comment]
yes I did

**Comment by Shreehar01** [comment]
You need to run the `npm install` command for both the client and server directory? Did you do it? If yes, then I am assuming you might be having this issue because of older version of node. Try upgrading it and then run the install and start command again.
